test1/booktest/urls.py
from django.contrib import admin
from  django.urls import path
from . import views


# 应用命名空间
app_name = 'booktest'

# 应用的urls文件
urlpatterns = [
	path('', views.index),				# 配置应用的首页面的url
	path('welcome/', views.welcome, name = 'welcome'),	# 配置应用的其他页面的url
	path('books/', views.books),
	path('books/<int:bid>/', views.detail),
	path('create/', views.create, name = 'cre'),
	path('delete<int:bid>/', views.delete, name='delete'),
	path('showarg<int:num>/', views.show_arg),
	path('login/', views.login),
	path('login_check/', views.login_check, name ='log'),
	path('web', views.search, name='search'),			# 查询
	path('rev/', views.rev, name='rev'),			# 重定向到 error/100/200
	path('error/<int:a>/<int:b>/', views.error, name='loose'),
	path('page/<int:page>',views.page),		# 默认值设置，需要设置俩个URL
	path('page/', views.page),					# 默认值设置
	path('extends', views.extends, name='extends'),		# 模板继承
	path('cookie_set/', views.cookie_set, name='cookie'),
	path('set_session', views.set_session),
	path('get_session', views.get_session),
	path('change_pwd', views.change_pwd),
	path('change_pwd_action', views.change_pwd_action, name='pwd'),	#密码处理
	path('verify_code/', views.verify_code),					# 验证码
	path('upload_pic', views.upload_pic),
	path('upload_handle', views.upload_handle, name='upload_handle'),
	path('show_books/', views.show_books),						# 分页展示的默认页
	path('show_books/<int:pindex>/', views.show_books, name='showpage'),	# 分页展示
	path('csstest/', views.csstest),						# 样式表测试
	path('default', views.default, name='default'),			# 首页布局
	path('mobile',views.mobile, name='moblie'),				# 移动布局测试
	path('rem', views.rem, name="rem"),						# 移动首页
	path('jquerytest', views.jquerytest),					# jquery 测试
	path('jsontest', views.jsontest),						# ajax请求处理
	path('bootstrap', views.bootstrap),						# bootstrap 测试
]	

test1/test1/urls.py
from django.contrib import admin
from django.urls import path

# 导入包含的包
from django.urls import include

# 项目的url文件
urlpatterns = [
    path('admin/', admin.site.urls),		#配置项目
    path('', include('booktest.urls')),				#配置应用
    path('', include('booktest.urls', namespace='news')),
    path('paper/', include('booktest.urls', namespace='paper')),
]

test1/booktest/models.py
from django.db import models

# Create your models here.
# 


# 自定义图书模型管理器类
class BookInfoManager(models.Manager):
	''' 图书模型管理器 '''
	# 1、改变查询的结果集
	def all(self):
		# 1、调用父类的all， 获取所有数据
		books = super().all()		# 这是一个 QuerySet
		# 2、对数据进行过滤
		books = books.filter(isDelete=False)
		# 3、 返回books
		return books

	# 2、封装函数： 操作模型类对应的数据表(增删改查)
	def create_book(self, btitle, bpub_date):
		# 创建一个图书对象 
		# book = BookInfo()
		# 每一个模型类的对象都有一个模型类 model ; 即使模型类的名称改变了，也不影响封装的函数
		# 创建一个模型类对象
		model_class = self.model
		book = model_class()
		book.btitle = btitle
		book.bpub_date = bpub_date
		# 保存到数据库
		book.save()
		# 返回对象
		return book



# 一类
# 图书类
class BookInfo(models.Model):
	'''
		图书模型类
	'''

	# 书名，字符串类型，长度20
	btitle = models.CharField('书名',max_length=20)
	# 出版日期, 日期类型
	bpub_date = models.DateField()
	# 阅读量
	bread = models.IntegerField(default=0)
	# 评论量
	bcomment = models.IntegerField(default=0)
	# 删除标记
	isDelete = models.BooleanField(default=False)

	# 重写 str 方法 ; 后台管理里面直接显示 图书名称 btitle
	def __str__(self):
		return self.btitle

	# 自定义一个函数 比如归类, 可以在后天添加自定义类
	def title(self):
		return self.btitle
	# title在后台显示的别名
	title.short_description = '自定义书名'



	## 增加类方法 （通常不会放在这里，这里是定义类，而不是操作方法；一般会放在 图书模型管理器中）
	# @classmethod
	# def create_book(cls, btitle, bpub_date):
	# 	# 1、创建一个图书对象
	# 	obj = cls()
	# 	obj.btitle = btitle
	# 	obj.bpub_date = bpub_date
	# 	# 2、 保存进数据库
	# 	obj.save()
	# 	# 3、 返回obj
	# 	return obj


	#  实例图书模型管理器
	objects = BookInfoManager()


	class Meta():
		''' 元选项： 改名等用处 '''
		# 指定BookInfo生成的数据表名为 bookinfo，而不是 booktest_bookinfo 
		db_table = 'bookinfo'
		# 后台表显示的别名
		verbose_name_plural = '图书'
		# 后台表数据的别名
		verbose_name = '图书列表'
		# 排序
		ordering = ['id'] 



# 多类
# 英雄人物类
class HeroInfo(models.Model):
	'''
		英雄人物模型表

		名 		hname
		性别	hgender
		年龄	hage
		备注	hcomment
		关系属性 book 建立图书类和英雄人物类之间的一对多关系
	'''

	choices = [
		('male', '男'),
		('female', '女')	
	]


	# 名称
	hname = models.CharField('名称',max_length=20,unique=True)
	# 性别，bool类型，指定默认值，False 代表男
	hgender = models.CharField(verbose_name='性别',max_length=10,choices=choices,default='male')	

	# 定义关系属性，一类的类名
	# 关系属性对应表的字段名 格式： 关系属性名_id  表名  hbook_id
	# 2.0版本后 一定要设置参数  on_delete ，不然会报错
	hbook = models.ForeignKey('BookInfo', verbose_name='书名' , on_delete=models.CASCADE)				# h.hbook = b  b是BookInfo()类属性;
	# 备注
	hcomment = models.TextField(verbose_name='介绍')
	# 删除标记
	isDelete = models.BooleanField('标记',default=False)

	# 重写 str 方法 ; 后台管理里面直接显示 英雄名称 hname
	def __str__(self):
		return self.hname



#
class AreaInfo(models.Model):
	'''地区模型类'''
	# 地区名称
	atilte = models.CharField(max_length=20,db_column='title')
	# 关系属性，代表当前地区的父级地区
	# 自关联
	aparent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)






class PicTest(models.Model):
	''' 上传图片 '''
	gpic = models.ImageField(upload_to='booktest')

test1/booktest/views.py
# 模板包 封装好的。不用分步骤去使用模板文件
#  redirect 网页跳转包
#  render 是渲染
#  reverse 反向解析
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, JsonResponse
# 导入加载模板文件包
from django.template import loader
# 导入定义模板上下文的包
from django.template import RequestContext
# 导入模型类包
from .models import BookInfo, BookInfoManager, PicTest
# 时间包
from datetime import date
# 重定向包
from django.http import HttpResponseRedirect
# 路径分离
from django.urls import resolve
# 导入配置项
from django.conf import settings
# 分页包
from django.core.paginator import Paginator

# Create your views here.


#=================================================
#
#	基础篇
#	
#==================================================



# 1、定义视图函数，和M 和T 进行交互
# 2、进行url配置， 建立url地址和视图的对应关系
# http://127.0.0.1:8000/index
# 就是普通的函数，但是必须有个 request 参数
def index(request):
	'''
		进行处理，请求和返回，和M 和T 进行交互
	'''
	# HttpResponse 必须要导入库
	# return HttpResponse("hello world")

	# # 使用模板文件
	# # 1、加载模板文件,	返回模板对象
	# temp = loader.get_template('booktest/index.html')

	# # 2、定义模板上下文， 给模板文件传递数据
	# # 需要导入包。 RequestContext
	# # 第一个参数是request 第二个参数是 传递的数据 是个字典，键值队
	# context = RequestContext(request, {'':''})

	# # 3、模板渲染 ： 产生标准的html内容
	# res_html = temp.render(context)
	
	# # 4、返回给浏览器
	# return HttpResponse(res_html)
	
	return render(request, 'booktest/index.html', {'content': 'hello world!','list': list(range(1,10))})


# /csstest
def csstest(request):
	''' css样式测试 '''
	return render(request, "booktest/csstest.html")

# /default
def default(request):
	''' 首页布局  '''
	return render(request, "booktest/default.html")

# /mobile
def mobile(request):
	''' 移动布局 '''
	return render(request, "booktest/mobile.html")

# /rem
def rem(request):
	''' 移动首页 '''
	return render(request, "booktest/rem.html")

# /jquerytest
def jquerytest(request):
	''' 移动首页 '''
	return render(request, "booktest/jquerytest.html")

# /jsontest
def jsontest(request):
	''' ajax请求处理 ---返回json数据 '''
	return JsonResponse({'res':1})

# /bootstrap
def bootstrap(request):
	''' bootstrap的实例 '''
	return render(request, "booktest/bootstrap.html")


# 由于导入了 render 包，模板文件就不用像index那么去写。 直接调用
def welcome(request):

	http_list = [
		'<h1>完整的URL地址:&nbsp;<span style="color:red">%s</span></h1>' % request.get_raw_uri(),
		'<h1>完整路径:&nbsp;<span style="color:red">%s</span></h1>' % request.get_full_path(),
	]

	return HttpResponse(http_list)




# 查找书籍列表
def books(request):

	# 获取图书列表, 通过model获取
	books = BookInfo.objects.all()

	return render(request, 'booktest/books.html', {'books': books })


# 查找图书相关英雄信息
def detail(request, bid):

	# 根据bid查询图书信息
	book = BookInfo.objects.get(id=bid)

	# 查询和book关联的英雄信息
	heros = book.heroinfo_set.all()

	# 使用模板 传递数据
	return render(request, 'booktest/detail.html', {'book': book, 'heros':heros})



#  新增页面
def create(request):
	''' 新增一本图书 '''

	# 1、创建BookInfo对象
	# b = BookInfo()
	# b.btitle = '新流星蝴蝶剑'
	# b.bpub_date = date(1990,1,1)
	# # 2、保存进数据库
	# b.save()
	# # 3、返回应答, 让浏览器再访问 /books
	# # return HttpResponse('OK')
	
	b = BookInfo.objects.create_book('笑傲江湖', '1990-1-14')
	# 网页重定向
	return HttpResponseRedirect('/books')



def delete(request, bid):
	''' 删除点击的图书 '''

	# 1、通过bid获取图书对象
	book = BookInfo.objects.get(id=bid)
	# 2、删除
	book.delete()
	# 3、重定向，让浏览器还是访问 /books
	return HttpResponseRedirect('/books')
	


# 捕获url参数
def show_arg(request, num):
	return HttpResponse(num)



# 查询
# 
def search(request):
	''' 通过url中的get属性查询 '''
	search = request.GET.get('query')
	return HttpResponse('<h1>{}</h1>'.format(search))



# 默认值设置
def page(request, page=100):
	return HttpResponse('<h1>{}</h1>'.format(page))




# 继承母版
def extends(request,):
	context = {	
		'age': 18,
		'books': ['html', 'python', 'django', 'css', 'javascript'],
		'turorial':{
			'title':'html',
			'author':'chan',
			'price': 99.00
		},
		'empty': '空的列表',
		'value': 100,
		'teacher':{
			'english':{
				'type': 'us'
			},
		},
	}
	return render(request, 'booktest/extends.html', context=context)








#================================================
#
#
#	反向解析  (动态地址)
#	
#================================================
#
# 用到三个包，一个重定向redireect  一个反向解析 reverse  一个路径分离 resolve




# 反向解析
# 从首页跳转到 /error/
def error(request, a, b):
	sum = a + b
	return HttpResponse('<h1 style="color:red;"">{}</h1>'.format(request.path))


# 反向解析重定向
# /rev  重定向到 /error/100/200
def rev(request):
	# 获取路径 
	path = request.path
	# 路径分离 得到项目urls.py中应用名namespace
	current_namespace = resolve(path).namespace
	# 获取完整的url
	url = reverse('{}:loose'.format(current_namespace), kwargs={'a':100, 'b':200})
	return redirect(url)







#============================================================================
#
#		登录页面
#		
#============================================================================
#
#



# 装饰器函数
def login_required(view_func):
	''' 登录判断装饰器 '''
	def wrapper(request, *view_args, **view_kwargs):
		# 判断用户是否登录
		if request.session.has_key('islogin'):
			# 用户已登录, 调用对应的视图
			return view_func(request,*view_args, **view_kwargs)
		else:
			# 用户未登录，跳转到首页
			return redirect('/login')

	return wrapper




# /login
def login(request):
	'''显示登录页面'''
	# 判断用户是否登录
	if request.session.has_key('islogin'):
		# 用户已登录，跳转到修改密码页面
		return redirect('/change_pwd')
	else:
		# 用户登录
		# 获取cookie username
		if 'username' in request.COOKIES:
			# 获取记住的用户名
			username = request.COOKIES['username']
		else:
			username = ''

		return render(request, 'booktest/login.html', {'username': username})



# 登录检验跳转
def login_check(request):
	'''登录校验视图'''

	# 1、 获取提交的用户名和密码
	# print(type(request.POST))
	# print(request.POST)
	username = request.POST.get('username')
	password = request.POST.get('password')
	remember = request.POST.get('remember')

	# 2、 获取用户输入的验证码 
	user_vcode = request.POST.get('vcode')
	# 获取sessin中保存的验证码
	session_vcode = request.session.get('verifycode')
	# 进行验证码校验
	if user_vcode != session_vcode:
		# 不正确，跳转到登录页面
		return redirect("/login")

	# 3、 进行登录的校验
	# 根据用户名和密码查找数据库
	# 模拟： admin 123
	if username == 'admin' and password == '123':
		# 用户名和密码正确，跳转到修改密码页面
		response =  redirect('/change_pwd')
		# 判断是否需要记住用户名
		if remember == 'on':
			# 设置cookie 过期时间
			response.set_cookie('username', username, max_age=7*24*3600)
		# 记住用户登录状态
		# 只有session中有 islogin， 就认为用户已登录
		request.session['islogin'] = True
		# 设置session过期时间，关闭浏览器就过期
		request.session.set_expiry(0)
		# 记住用户登录名
		request.session['username'] = username
		return response	
	else:
		# 不正确，跳转到登录页面
		return redirect("/login")



#
# 登录后跳转修改密码界面
# 装饰器 判断用户是否登录。
@login_required
def change_pwd(request):
	''' 修改密码 '''
	return	render(request, 'booktest/change_pwd.html')



# /change_pwd_action   别名 pwd
## 修改密码处理
# 装饰器 判断用户是否登录。
@login_required
def change_pwd_action(request):
	''' 模拟密码处理 '''
	# 1、获取新密码
	pwd = request.POST.get('pwd')
	# 获取用户名
	username = request.session.get('username')
	# 2、实际开发的时候：修改对应数据库中的内容
	# 3、返回一个应答
	return HttpResponse('%s修改密码为：%s'%(username,pwd))









#=======================================================================================================
#
# cookie  session
# 
# =====================================================================================================
# 




# /cookie_set
def cookie_set(request):
	''' 
		设置cookie信息
	'''
	response = HttpResponse("设置cookie，在表头查看")
	# 设置一个cookie信息，名字为name,值为value
	# max_age=14*24*3600 设置多少秒过期； expires = datetime.now() + timedelta(days=14) 两周过期
	response.set_cookie('name', 'value')		
	#  返回response . request.COOKIES 读取cookie
	print(request.COOKIES)
	return response



# /set_session
def set_session(request):
	'''
		设置session
	'''
	request.session['username'] = 'admin'
	request.session['age'] = 18
	return HttpResponse('设置session')



# /get_session
def get_session(request):
	'''
		读取session
	'''
	username = request.session['username']
	age = request.session['age']
	return HttpResponse(username+':'+str(age))









# ========================================================================================
#
##   验证
#
#=========================================================================================

# 验证码
from PIL import Image, ImageDraw, ImageFont
from django.utils.six import BytesIO

def verify_code(request):
    #引入随机函数模块
    import random
    #定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), 255)
    width = 100
    height = 25
    #创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    #创建画笔对象
    draw = ImageDraw.Draw(im)
    #调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    #定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    #随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    #构造字体对象，ubuntu的字体路径为“/usr/share/fonts/truetype/freefont”
    font = ImageFont.truetype('c:\Windows\Fonts\msyh.ttf', 23)
    #构造字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    #绘制4个字
    draw.text((5, -2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, -2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, -2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, -2), rand_str[3], font=font, fill=fontcolor)
    #释放画笔
    del draw
    #存入session，用于做进一步验证
    request.session['verifycode'] = rand_str
    #内存文件操作
    buf = BytesIO()
    #将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    #将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')



#=================================
#
#
#	上传图片
#	
#=================================
#导入2个包		一个settings  一个视图模型
#
#
# https://docs.djangoproject.com/zh-hans/2.2/topics/http/file-uploads/

def upload_pic(request):
	'''显示上传图片页面'''

	return render(request,'booktest/upload_pic.html')



def upload_handle(request):
	''' 上传图片处理 '''

	#1、获取上传文件的处理对象(根据字典里的名字获取)
	pic = request.FILES['pic']
	# print(pic.name)		# 打印名称
	# pic.chunks()			# 分块返回内容

test1/templates/booktest/books.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>书籍名称</title>
</head>
<body>
	图书内容如下：<br>
	<ul>
		{% for book in books %}
		<li><a href= '{{ book.id }}/' >{{ book.btitle }}</a>--<a href='/delete{{ book.id }}'>删除</a></li>
		{% endfor %}
	</ul>
<a href={%url 'news:cre'%}> 新增 </a>
</body>
</html>

test1/templates/booktest/change_pwd.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<form method='post' action={%url "news:pwd"%}>
		{% csrf_token %}
		新密码<input type="password" name='pwd'>
		<input type="submit" value="确认修改">
	</form>
</body>
</html>

test1/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>显示图书关联的英雄信息</title>
</head>
<body>
<h1>{{ book.btitle }}</h1>	
英雄信息如下：<br>
<ul>
	{% for hero in heros %}
		<li>{{ hero.hname }} -- {{ hero.hcomment }}</li>
	{% empty %}
		<li>没有英雄信息</li>
	{% endfor %}
</ul>
</body>
</html>

test1/templates/booktest/footer.html
<div class="footer">
	<ul>
		<li>Index</li>
		<li>Html</li>
		<li>CSS</li>
		<li>Python</li>
		<li>Django</li>
	</ul>
</div>

test1/templates/booktest/index.html
<!-- 加载自定义过滤器 -->
{%load filters%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>模板文件</title>
	<style>
		.header{height: 50px; background-color: darkturquoise; margin:-8px;}
		.content{height: 700px; }
		.footer{height: 50px; background-color: lightpink ;}
		.red{background-color: red}
		.yellow{background-color: yellow}
		.green{background-color: green}

		ul.f1{
			width: 60px;
			display: inline-block;
		}

		.menu{
			width: 694px;
			height: 50px;
			margin: 50px auto 0;
			/*background-color: gray;		*/
			font-size: 0px;	
			padding:0;						/* 去掉li的padding */
		}
		.menu a{
			width: 98px;						
			height: 48px;					/* 标签的高度， */			
			font-size: 16px;					
			border: 1px solid gold;			/* 边框大小 类型 颜色 */
			font-style: 'Microsoft Yahei';
			display: inline-block;			/* 内联元素转为内联块元素 */
			margin-left: -1px;				/* 边框合并 */
			text-align:center;				/* 文字水平居中 */
			line-height:50px;				/* 文字的间距 设置文字垂直居中 */
			text-decoration:none;			/* 去下划线 */
			color:pink;						/* 字体颜色 */
		}
		.menu a:hover{						/* 伪类 */
			background-color: #FFA500;		/* 鼠标滑过的背景颜色 */
			color:#fff;						/* 字体颜色 */
		}

	

		/*  常用列表来制作菜单 */


		.menu1{
			width: 694px;
			height: 50px;
			margin: 0 auto;			/* 整体布局 	*/
			/*background-color: gray;		*/
			list-style: none;				/* 去掉li的圆点 */
			padding:0;						/* 去掉li的padding */

			position: fixed;				
			left:50%;
			top:0;
			margin-left: -347px;

		}
		.menu1 li a{
			width: 98px;						
			height: 48px;					/* 标签的高度， */							
			border: 1px solid gold;			/* 边框大小 类型 颜色 */
			font: normal 16px/50px 'Microsoft Yahei';		/* 字体设置：加粗 大小/行间距 字体 */
			margin-left: -1px;				/* 边框合并 */
			text-align:center;				/* 文字水平居中 */
			text-decoration:none;			/* 去下划线 */
			color:pink;						/* 字体颜色 */
			float:left;						/* 左浮动 */
		}
		.menu1 a:hover{						/* 伪类 */
			background-color: #FFA500;		/* 鼠标滑过的背景颜色 */
			color:#fff;						/* 字体颜色 */
		}



	</style>
</head>
<body>
	<div class = "header"> 导航栏 </div>
	<div class = "content">
		<h1> 这是一个模板文件 </h1>
		使用模板变量： <br/>
		{{ content }} <br/>
		使用列表：<br/>
		{{ list }} <br>
		for 循环：<br>
		<ul class="f1">
			{% for i in list %}
			
			<!-- 多行注释  -->
			{% comment %}
				{% if i <= 2 %}
					<li class="red">{{ forloop.counter }}--{{ i }}</li>
				{% elif i <= 5 %}
					<li class="yellow">{{ forloop.counter }}--{{ i }}</li>
				{% else %}
					<li class="green">{{ forloop.counter }}--{{ i }}</li>
				{% endif %}
			{% endcomment %}

				<!-- 自定义过滤器  -->
				{% if i|mm %}
					<li class="red">{{ forloop.counter }}--{{ i }}</li>
				{% else %}
					<li class="green">{{ forloop.counter }}--{{ i }}</li>
				{% endif %}

			{% endfor %}
		</ul>

		<!-- 内容查询 -->
		<form action={% url 'booktest:search' %}>
			<input type="text" name= 'query'>
		</form>



		<a href="{% url 'news:loose' a=100 b=200 %}" >  路径页 </a>


		<div class="menu">
			<a href="#">首页</a>
			<a href="#">公司简介</a>
			<a href="#">解决方案</a>
			<a href="#">公司新闻</a>
			<a href="#">行业动态</a>
			<a href="#">招贤纳才</a>
			<a href="#">联系我们</a>	
		</div>
	
		<ul class="menu1">
			<li><a href="#">首页</a></li>
			<li><a href="#">公司简介</a></li>
			<li><a href="#">解决方案</a></li>
			<li><a href="#">公司新闻</a></li>
			<li><a href="#">行业动态</a></li>
			<li><a href="#">招贤纳才</a></li>
			<li><a href="#">联系我们</a></li>
		</ul>

	</div>	
	<div class='footer'> 页脚 </div>

</body>
</html>

test1/templates/booktest/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>登录页面</title>
</head>
<body>
	POST: 提交的参数请求头，数据安全性要求比较高的时候用 post
	GET: 提交的参数在 url 中
<form method='post' action={%url 'news:log'%}>
	<!-- 防止csrf 攻击，只针对post提交的表单 -->
	{% csrf_token %}
	同户名：<input type="text" name='username' value="{{ username }}"><br>
	密 码：<input type="password" name='password'><br>
	<input type="checkbox" name='remember'>记住用户名<br/>
	<!-- 验证码 -->
	<input type="text" name="vcode"><img src="/verify_code"><br>
	<input type="submit" value='登录'>
</form>
</body>
</html>

test1/templates/booktest/show_books.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>分页显示</title>
</head>
<body>
<ul>
	<!-- 两者效果相同 -->
	{# {% for book in page.object_list %} #}
	<!-- 显示页内容，默认为第1页  -->	
	{% for book in page %}
	<li>{{ book }}</li>
	{% endfor %}
</ul>

<!-- 判断是否有上一页 -->
{% if page.has_previous %}
	<a href={% url "news:showpage" page.previous_page_number %}>&lt;上一页</a>
{% endif %}

<!-- page_range是页码的列表 -->
{% for pindex in page.paginator.page_range %}
	<!-- 判断是否为当前页 -->
	{% if pindex == page.number %}
		{{ pindex }}
	{% else %}
		<a href={% url "news:showpage" pindex %}>{{ pindex }}</a>
	{% endif  %}
{% endfor %}

<!-- 判断是否有下一页 -->
{% if page.has_next %}
	<a href={% url "news:showpage" page.next_page_number %}>下一页&gt;</a>
{% endif %}
<br>
<br>
<!-- 下拉列表框 -->
<select name="" id="city">
	<option value="">---请选择城市---</option>
</select>

</body>
</html>

test1/templates/booktest/upload_pic.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>上传图片</title>
</head>
<body>
	<form method='post' enctype="multipart/form-data" action={% url "booktest:upload_handle" %}>
		{% csrf_token %}
		<input type="file" name='pic'><br/>
		<input type="submit" value="上传">


	</form>
</body>
</html>